name: xeus-kernels
channels:
  - https://prefix.dev/emscripten-forge-4x
  - https://prefix.dev/conda-forge
dependencies:
  - xeus-lua
  - xeus-python
  - matplotlib
  - numpy
  - scipy
  - sympy
  - pandas
  - pillow
  - pillow-heif
  - aiohttp
  - pycairo
  - fonttools
  - xeus-cpp
  - boost-cpp
  - nlohmann_json
  - cairo
  - freetype
  - zlib
  - openssl
  - xeus-sqlite
  - xeus-javascript
