name: xeus-kernels
channels:
  - https://prefix.dev/emscripten-forge-4x
  - https://prefix.dev/conda-forge
dependencies:
  - xeus-lua
  - xeus-cpp
  - boost-cpp
  - nlohmann_json
  - cairo
  - freetype
  - zlib
  - openssl
  - sqlite
  - xeus-sqlite
  - xeus-javascript
