name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Download MicroMamba
        run: |
          curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | sudo tar -C /usr/local -xvj bin/micromamba
          eval "$(micromamba shell hook -s posix)"
      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Download latest Pyodide from its Github site
        run: |
          gh release download -R pyodide/pyodide -p $(gh release view -R pyodide/pyodide | grep -E pyodide-[0-9]+\.[0-9]+\.[0-9]+\.tar\.bz2 | sed -E "s/.*(pyodide-[0-9]+\.[0-9]+\.[0-9]+\.tar\.bz2).*/\1/") -O pyodide.tar.bz2 --clobber
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Build the JupyterLite site
        run: |
          cp README.md content
          jupyter lite build --contents content --output-dir dist --pyodide=pyodide.tar.bz2
      - name: Package the artifact
        run: |
          cd dist
          zip -ur9 ../jupyterlite.zip *
      - name: Upload GithubPages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: jupyterlite.zip
          path: ./jupyterlite.zip

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
